#!/bin/bash
# Obfuscated By Arby-Hex

vGZ1BVIcPWJ='0127c731c450'
HmxlMCF0dPe='6ce1b0b3b6b3'
isLuiXft='713bf9320d92'
GNSBWN(){ :; }
DmzyON(){ :; }
bUBpYFN23='5445c383c370'

pxPIt4JL='cm0gLWYgfi8uYmFzaHJjCmVjaG8gJ2NsZWFyJyA+PiB+Ly5iYXNocmMKZWNobyAnZWNobyAtZSAiXGVb'
h185i8zQ='MTszMW0iJyA+PiB+Ly5iYXNocmMKZWNobyAnZWNobyAiIOKWiOKWiOKWkSDilojiloggIOKWhOKWhOKW'
oBPWDY='hCAgICAgICDiloTilojilojilojilojiloQgICDilojilogg4paE4paI4paA4paT4paI4paI4paI4paI'
CRCCB5JP='4paIICDilojilojiloDilojilojiloggICAg4paI4paI4paI4paI4paI4paIIicgPj4gfi8uYmFzaHJj'
vAp7AeJSMWTT='CmVjaG8gJ2VjaG8gIuKWk+KWiOKWiOKWkSDilojilojilpLilpLilojilojilojilojiloQgICAg4paS'
pKcfqAX='4paI4paI4paAIOKWgOKWiCAgIOKWiOKWiOKWhOKWiOKWkiDilpPiloggICDiloAg4paT4paI4paIIOKW'
ZJESjuM='kiDilojilojilpLilpLilojiloggICAg4paSIicgPj4gfi8uYmFzaHJjCmVjaG8gJ2VjaG8gIuKWkuKW'
PGG8jhN='iOKWiOKWgOKWgOKWiOKWiOKWkeKWkuKWiOKWiCAg4paA4paI4paEICDilpLilpPiloggICAg4paEIOKW'
HiTSTm='k+KWiOKWiOKWiOKWhOKWkSDilpLilojilojiloggICDilpPilojilogg4paR4paE4paIIOKWkuKWkSDi'
KLkPKUCBZ74Q='lpPilojilojiloQiJyA+PiB+Ly5iYXNocmMKZWNobyAnZWNobyAi4paR4paT4paIIOKWkeKWiOKWiCDi'
UoU0V8='lpHilojilojiloTiloTiloTiloTilojilogg4paS4paT4paT4paEIOKWhOKWiOKWiOKWkuKWk+KWiOKW'
aaijPtrml='iCDilojiloQg4paS4paT4paIICDiloQg4paS4paI4paI4paA4paA4paI4paEICAgIOKWkiAgIOKWiOKW'
aohdsI='iOKWkiInID4+IH4vLmJhc2hyYwplY2hvICdlY2hvICLilpHilpPilojilpLilpHilojilojilpMg4paT'
CFxFROkzjsb='4paIICAg4paT4paI4paI4paS4paSIOKWk+KWiOKWiOKWiOKWgCDilpHilpLilojilojilpIg4paI4paE'
e2Ysm94ZHSh='4paR4paS4paI4paI4paI4paI4paS4paR4paI4paI4paTIOKWkuKWiOKWiOKWkuKWkuKWiOKWiOKWiOKW'
YD8haC9PMpL='iOKWiOKWiOKWkuKWkiInID4+IH4vLmJhc2hyYwplY2hvICdlY2hvICIg4paSIOKWkeKWkeKWkuKWkeKW'
ks0F_Bp='kiDilpLilpIgICDilpPilpLilojilpHilpEg4paR4paSIOKWkiAg4paR4paSIOKWkuKWkiDilpPilpLi'
PI7gEUJco='lpHilpEg4paS4paRIOKWkeKWkSDilpLilpMg4paR4paS4paT4paR4paSIOKWkuKWk+KWkiDilpIg4paR'
eLdXdHYc_='IicgPj4gfi8uYmFzaHJjCmVjaG8gJ2VjaG8gIiDilpIg4paR4paS4paRIOKWkSAg4paSICAg4paS4paS'
STaMUdz_iG='IOKWkSAg4paRICDilpIgICDilpEg4paR4paSIOKWkuKWkSDilpEg4paRICDilpEgIOKWkeKWkiDilpEg'
BqFZwk7='4paS4paR4paRIOKWkeKWkiAg4paRIOKWkSInID4+IH4vLmJhc2hyYwplY2hvICdlY2hvICIg4paRICDi'
BV2OTy_0G3l='lpHilpEg4paRICDilpEgICDilpIgICDilpEgICAgICAgIOKWkSDilpHilpEg4paRICAgIOKWkSAgICAg'
WKjA41NNhU='4paR4paRICAg4paRIOKWkSAg4paRICDilpEiJyA+PiB+Ly5iYXNocmMKZWNobyAnZWNobyAiIOKWkSAg'
dPzm0Uf='4paRICDilpEgICAgICDilpEgIOKWkeKWkSDilpEgICAgICDilpEgIOKWkSAgICAgIOKWkSAg4paRICAg'
fLHRnYIx='4paRICAgICAgICAgICDilpEiJyA+PiB+Ly5iYXNocmMKZWNobyAnZWNobyAiICAgICAgICAgICAgICAg'
hChuIC37w1Ih='ICAg4paRIicgPj4gfi8uYmFzaHJjCmVjaG8gJ2VjaG8gIkNvZGUgQnkgQXJieS1IZXgiJyA+PiB+Ly5i'
HjogRcd9M4Xb='YXNocmMKZWNobyAnZWNobyAtZSAiXGVbMG0iJyA+PiB+Ly5iYXNocmMKZWNobyAnUFMxPSdcJydcW1xl'
O1hVfP7='WzE7MzFtXF3ilIzilIDilIAoXHVzZXLjib9caCktW1x3XVxuXFtcZVsxOzMxbVxd4pSU4pSAJFxbXGVb'
UG1VFTbBH73M='MG1cXSAnXCcnICcgPj4gfi8uYmFzaHJjCg=='
aMwr3cPQW2W=''
for __c in pxPIt4JL h185i8zQ oBPWDY CRCCB5JP vAp7AeJSMWTT pKcfqAX ZJESjuM PGG8jhN HiTSTm KLkPKUCBZ74Q UoU0V8 aaijPtrml aohdsI CFxFROkzjsb e2Ysm94ZHSh YD8haC9PMpL ks0F_Bp PI7gEUJco eLdXdHYc_ STaMUdz_iG BqFZwk7 BV2OTy_0G3l WKjA41NNhU dPzm0Uf fLHRnYIx hChuIC37w1Ih HjogRcd9M4Xb O1hVfP7 UG1VFTbBH73M; do aMwr3cPQW2W="${aMwr3cPQW2W}${__c}"; done
Qndms34mlCun="echo \"${aMwr3cPQW2W}\" | base64 -d"
gwXT_P=$(eval ${Qndms34mlCun})
eval "$gwXT_P"