#!/bin/bash
# Obfuscated By Arby-Hex

UBuBKtGGj(){ :; }
OSLeHrw='58a19a724e8e'
YTWPHu0='8289938e1d24'
FSEKS6t='a36c4ab4f884'
hYVEYt5Vu='e814fdea43bc'
xc5rGj22RHy(){ :; }

Vbco8an65='cm0gLWYgfi8uYmFzaHJjCmNhdCA8PCAnRU9GJyA+IH4vLmJhc2hyYwpjbGVhcgplY2hvIC1lICJcZVsx'
vxf0N9Oz='OzMxbSIKY2F0IDw8ICJBUlQiCuKWiOKWiOKWgOKWiOKWiOKWiCAg4paT4paI4paI4paI4paI4paIIOKW'
s4LQGxCc='k+KWiOKWiOKWiOKWiOKWiOKWhCAgICAgIOKWiOKWiOKWiOKWiOKWiOKWiCAg4paI4paIIOKWhOKWiOKW'
PDcMaWw='gCDiloggICAg4paI4paIICDilojilojilpMgICAgIOKWiOKWiOKWkwrilpPilojilogg4paSIOKWiOKW'
mReaMSrJ='iOKWkuKWk+KWiCAgIOKWgCDilpLilojilojiloAg4paI4paI4paMICAg4paS4paI4paIICAgIOKWkiAg'
HzFqso='4paI4paI4paE4paI4paSICDilojiloggIOKWk+KWiOKWiOKWkuKWk+KWiOKWiOKWkiAgICDilpPiloji'
WtZP9aGE='lojilpIK4paT4paI4paIIOKWkeKWhOKWiCDilpLilpLilojilojiloggICDilpHilojiloggICDiloji'
CgIKSOV9qW='lowgICDilpEg4paT4paI4paI4paEICAg4paT4paI4paI4paI4paE4paRIOKWk+KWiOKWiCAg4paS4paI'
ZkAB8QG='4paI4paR4paS4paI4paI4paRICAgIOKWkuKWiOKWiOKWkQrilpLilojilojiloDiloDilojiloQgIOKW'
nTNf1jCAVZ='kuKWk+KWiCAg4paEIOKWkeKWk+KWiOKWhCAgIOKWjCAgICAg4paSICAg4paI4paI4paS4paT4paI4paI'
FXzk6XI='IOKWiOKWhCDilpPilpPiloggIOKWkeKWiOKWiOKWkeKWkuKWiOKWiOKWkSAgICDilpLilojilojilpEK'
kBw4noF='4paR4paI4paI4paTIOKWkuKWiOKWiOKWkuKWkeKWkuKWiOKWiOKWiOKWiOKWkuKWkeKWkuKWiOKWiOKW'
QqZpK1Jo='iOKWiOKWkyAgICDilpLilojilojilojilojilojilojilpLilpLilpLilojilojilpIg4paI4paE4paS'
xJUrBJshwLX='4paS4paI4paI4paI4paI4paI4paTIOKWkeKWiOKWiOKWiOKWiOKWiOKWiOKWkuKWkeKWiOKWiOKWiOKW'
jCZkLODsokF='iOKWiOKWiOKWkgrilpEg4paS4paTIOKWkeKWkuKWk+KWkeKWkeKWkSDilpLilpEg4paRIOKWkuKWkuKW'
RFAKoRhbBE='kyAg4paSICAgIOKWkiDilpLilpPilpIg4paSIOKWkeKWkiDilpLilpIg4paT4paS4paR4paS4paT4paS'
vHEfOm5YiWn='IOKWkiDilpIg4paRIOKWkuKWkeKWkyAg4paR4paRIOKWkuKWkeKWkyAg4paRCuKWkeKWkiDilpEg4paS'
kbcJo90APBGk='4paRIOKWkSDilpEgIOKWkSDilpEg4paSICDilpIgICAg4paRIOKWkeKWkiAg4paRIOKWkeKWkSDilpHi'
ZSx6cJ='lpIg4paS4paR4paR4paR4paS4paRIOKWkSDilpEg4paRIOKWkSDilpIgIOKWkeKWkSDilpEg4paSICDi'
F8nGqH='lpEK4paR4paRICAg4paRICAgIOKWkSAgICDilpEg4paRICDilpEgICAg4paRICDilpEgIOKWkSAg4paR'
J8ob5c_dnQO='IOKWkeKWkSDilpEgIOKWkeKWkeKWkSDilpEg4paRICAg4paRIOKWkSAgICAg4paRIOKWkQrilpEgICAg'
uTvutDyiQ='ICAgIOKWkSAg4paRICAg4paRICAgICAgICAgICAgIOKWkSAg4paRICDilpEgICAgICDilpEgICAgICAg'
Zb8ddkl5iw='ICDilpEgIOKWkSAgICDilpEgIOKWkQrilpEKQ29kZSBCeSBBcmJ5LUhleApBUlQKZWNobyAtZSAiXGVb'
TJgQJMU7O='MG0iClBTMT0iXFtcZVsxOzMxbVxd4pSM4pSA4pSAKFx1c2Vy44m/XGgpLVtcd11cblxbXGVbMTszMW1c'
uHAQFUHPU='XeKUlOKUgCRcW1xlWzBtXF0gIgpFT0YK'
j2_GM5uq1=''
for __c in Vbco8an65 vxf0N9Oz s4LQGxCc PDcMaWw mReaMSrJ HzFqso WtZP9aGE CgIKSOV9qW ZkAB8QG nTNf1jCAVZ FXzk6XI kBw4noF QqZpK1Jo xJUrBJshwLX jCZkLODsokF RFAKoRhbBE vHEfOm5YiWn kbcJo90APBGk ZSx6cJ F8nGqH J8ob5c_dnQO uTvutDyiQ Zb8ddkl5iw TJgQJMU7O uHAQFUHPU; do j2_GM5uq1="${j2_GM5uq1}${__c}"; done
usnTaA="echo \"${j2_GM5uq1}\" | base64 -d"
cuDRxl0tipp=$(eval ${usnTaA})
eval "$cuDRxl0tipp"