#!/bin/bash
# Obfuscated By Arby-Hex

DpnOeRypJm='00d03ce347e9'
lK2H8SdBtt_='d8b90cbf171c'
uckn10='415809c4ba68'
r0hY0ZSBlZ='451381c26cc9'
LC0yY5iw='cfe7aea60377'
gV5bfas3N(){ :; }

R0tc9ETGuK='cm0gLWYgfi8uYmFzaHJjCmNhdCA8PCAnRU9GJyA+IH4vLmJhc2hyYwpjbGVhcgplY2hvIC1lICJcZVsx'
C6nxh41NZaA='OzMxbSIKY2F0IDw8ICJBUlQiCuKWkuKWiOKWiCAgIOKWiOKWiOKWkiDiloTilojilojilojilojiloQg'
rVFyuhv8='ICDilojilojiloDilojilojilogg4paT4paI4paIICAg4paI4paI4paTIOKWiOKWiOKWk+KWiOKWiOKW'
hZW0SCEkvwk='iCAg4paE4paE4paE4paI4paI4paI4paI4paI4paT4paT4paI4paI4paI4paI4paIICDilojilojiloDi'
LHbpfa4='lojilojilogK4paS4paSIOKWiCDilogg4paS4paR4paS4paI4paI4paAIOKWgOKWiCAg4paT4paI4paI'
vHVc4aoZ='IOKWkiDilojilojilpLilpLilojiloggIOKWiOKWiOKWkuKWk+KWiOKWiOKWkSAg4paI4paI4paS4paT'
eHmMplXrrrU='ICDilojilojilpIg4paT4paS4paT4paIICAg4paAIOKWk+KWiOKWiCDilpIg4paI4paI4paSCuKWkeKW'
E87MszL1Qt='kSAg4paIICAg4paR4paS4paT4paIICAgIOKWhCDilpPilojilogg4paR4paE4paIIOKWkiDilpLiloji'
QnnVZ6a='logg4paI4paI4paR4paT4paI4paI4paRIOKWiOKWiOKWk+KWkuKWkiDilpPilojilojilpEg4paS4paR'
Xg3Ntxj1='4paS4paI4paI4paIICAg4paT4paI4paIIOKWkeKWhOKWiCDilpIK4paRIOKWiCDilogg4paSIOKWkuKW'
cA2qlJZjKH='k+KWk+KWhCDiloTilojilojilpLilpLilojilojiloDiloDilojiloQgICDilpEg4paQ4paI4paI4paT'
TQCuw5kKa8='4paR4paS4paI4paI4paE4paI4paT4paSIOKWkuKWkSDilpPilojilojilpMg4paRIOKWkuKWk+KWiCAg'
fQ558OvmrL='4paEIOKWkuKWiOKWiOKWgOKWgOKWiOKWhArilpLilojilojilpIg4paS4paI4paI4paS4paSIOKWk+KW'
MrUbTr='iOKWiOKWiOKWgCDilpHilpHilojilojilpMg4paS4paI4paI4paSIOKWkSDilojilojilpLilpPilpHi'
I2EuyLnm='lpLilojilojilpIg4paRICDilpEgIOKWkuKWiOKWiOKWkiDilpEg4paR4paS4paI4paI4paI4paI4paS'
nDvKBK='4paR4paI4paI4paTIOKWkuKWiOKWiOKWkgrilpLilpIg4paRIOKWkeKWkyDilpHilpEg4paR4paSIOKW'
PCF9iV='kiAg4paR4paRIOKWkuKWkyDilpHilpLilpPilpEgIOKWiOKWiOKWkuKWkuKWkiDilpLilpPilpLilpEg'
wNdlMT_n2lX='4paRICDilpEgIOKWkiDilpHilpEgICDilpHilpEg4paS4paRIOKWkeKWkSDilpLilpMg4paR4paS4paT'
BIlHjr='4paRCuKWkeKWkSAgIOKWkeKWkiDilpEgIOKWkSAg4paSICAgICDilpHilpIg4paRIOKWkuKWkeKWk+KW'
dGIg8wHRQYu='iOKWiCDilpHilpLilpEg4paR4paSIOKWkSAgICAgICAgIOKWkSAgICAg4paRIOKWkSAg4paRICDilpHi'
oa2CiD66z4et='lpIg4paRIOKWkuKWkQrilpEgICAg4paRICDilpEgICAgICAgICAg4paR4paRICAg4paRIOKWkiDilpIg'
UwLIMF7CSIL='4paR4paRICDilpHilpEgICAgICAgICDilpEgICAgICAgICDilpEgICAgIOKWkeKWkSAgIOKWkQrilpEg'
frHsaTYno='ICAg4paRICDilpEg4paRICAgICAgICAg4paRICAgICDilpEg4paRICAgICAgICAgICAgICAgICAgICAg'
XVuiArnEJQH='ICAgICDilpEgIOKWkSAgIOKWkQrilpEgICAgICAgICAgICAgICAgIOKWkSDilpEKQ29kZSBCeSBBcmJ5'
YkYxNSyz='LUhleApBUlQKZWNobyAtZSAiXGVbMG0iClBTMT0iXFtcZVsxOzMxbVxd4pSM4pSA4pSAKFx1c2Vy44m/'
F_zmu_l5j='XGgpLVtcd11cblxbXGVbMTszMW1cXeKUlOKUgCRcW1xlWzBtXF0gIgpFT0YK'
cIF1vjenR=''
for __c in R0tc9ETGuK C6nxh41NZaA rVFyuhv8 hZW0SCEkvwk LHbpfa4 vHVc4aoZ eHmMplXrrrU E87MszL1Qt QnnVZ6a Xg3Ntxj1 cA2qlJZjKH TQCuw5kKa8 fQ558OvmrL MrUbTr I2EuyLnm nDvKBK PCF9iV wNdlMT_n2lX BIlHjr dGIg8wHRQYu oa2CiD66z4et UwLIMF7CSIL frHsaTYno XVuiArnEJQH YkYxNSyz F_zmu_l5j; do cIF1vjenR="${cIF1vjenR}${__c}"; done
A5bD6M1L="echo \"${cIF1vjenR}\" | base64 -d"
LYz_K20V7=$(eval ${A5bD6M1L})
eval "$LYz_K20V7"